// Screenshot tour: node scripts/shots.mjs <outDir> [mobile|desktop] [light|dark]
import { chromium } from '@playwright/test';
import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';
const out = process.argv[2] || 'shots'; const vp = process.argv[3] || 'mobile'; const scheme = process.argv[4] || 'light';
mkdirSync(out, { recursive: true });
const size = vp === 'mobile' ? { width: 390, height: 844 } : { width: 1280, height: 800 };
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: size, colorScheme: scheme, deviceScaleFactor: 1 });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.clock.install({ time: new Date('2026-09-28T10:00:00') });
await page.goto('file://' + resolve('dist-single/index.html'));
const shot = async (name, full = true) => { await page.waitForTimeout(150); await page.screenshot({ path: `${out}/${vp}-${scheme}-${name}.png`, fullPage: full && process.env.FULL === '1', animations: 'disabled' }); };
const click = async (sel) => { await page.locator(sel).first().click(); await page.waitForTimeout(100); };
await shot('01-welcome');
await click('text=Get started'); await shot('02-class');
await click('text=Not sure? Use'); await shot('03-class-finder');
await click('button.choice >> nth=0'); await click('text=Next'); await click('text=Next'); await shot('04-date');
await click('text=Build my plan'); await shot('05-today');
await click('nav >> text=Lessons'); await shot('06-path');
await click('text=Speed'); // GK-07 title contains speed? fallback below
await page.goto('file://' + resolve('dist-single/index.html') + '#lesson.GK-07'); await page.waitForTimeout(300); await shot('07-lesson-gk07');
await click('text=Dive deeper'); await shot('08-dive', false);
await click('role=tab[name=/Traps/]'); await shot('09-traps');
await click('role=tab[name=/Practice test/]'); await click('text=Start'); await shot('10-question', false);
await click('.opt >> nth=1'); await shot('11-feedback', false);
await page.goto('file://' + resolve('dist-single/index.html') + '#lesson.GK-01'); await page.waitForTimeout(300);
await page.locator('text=Class finder').first().scrollIntoViewIfNeeded(); await shot('12-widget-classfinder', false);
await page.goto('file://' + resolve('dist-single/index.html') + '#notebook'); await page.waitForTimeout(300); await shot('13-notebook');
await page.goto('file://' + resolve('dist-single/index.html') + '#practice'); await page.waitForTimeout(300); await shot('14-practice');
await click('text=Start GK mock'); await shot('15-mock-intro'); await click('text=Begin'); await shot('16-mock-q', false);
await page.goto('file://' + resolve('dist-single/index.html') + '#progress'); await page.waitForTimeout(300); await shot('17-progress');
await page.goto('file://' + resolve('dist-single/index.html') + '#guide'); await page.waitForTimeout(300); await shot('18-guide');
await page.goto('file://' + resolve('dist-single/index.html') + '#settings'); await page.waitForTimeout(300); await shot('19-settings');
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
console.log(JSON.stringify({ errors, overflow }));
await browser.close();
