#!/usr/bin/env python3
"""Regenerate EXCHANGE/STATUS.md — a plain-language dashboard of the whole
multi-agent system, so the operator never has to open the individual files.
Single writer: integrator. Reads AGENTS.json, tasks.json, scores.json (if
present), and the git log; writes STATUS.md. Pure stdlib."""
import json, subprocess, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def load(p, default):
    fp = os.path.join(ROOT, p)
    if not os.path.exists(fp):
        return default
    try:
        return json.load(open(fp))
    except Exception:
        return default

def git(args):
    try:
        return subprocess.run(["git"] + args, cwd=ROOT, capture_output=True,
                              text=True, timeout=20).stdout.strip()
    except Exception:
        return ""

STATE_EMOJI = {"assigned": "🟡 assigned", "in_progress": "🔵 building",
               "delivered": "🟣 in review", "revise": "🟠 revising",
               "accepted": "🟢 accepted", "integrated": "✅ integrated",
               "abandoned": "⚪ abandoned"}

def main():
    agents = load("EXCHANGE/AGENTS.json", {})
    ledger = load("EXCHANGE/tasks.json", {"tasks": []})
    scores = load("EXCHANGE/scores.json", {"agents": {}})
    proto = agents.get("protocol_version", "?")
    tasks = ledger.get("tasks", [])
    open_t = [t for t in tasks if t["state"] not in ("integrated", "abandoned")]
    done_t = [t for t in tasks if t["state"] == "integrated"]
    last5 = git(["log", "-5", "--format=%h  %s"]).splitlines()

    L = []
    L.append("# STATUS — multi-agent system dashboard")
    L.append("")
    L.append(f"Auto-generated by `tools/status.py` (single writer: integrator). "
             f"Protocol **v{proto}**. This is the plain-language mirror of the "
             f"machine files — read this, not the JSON.")
    L.append("")
    L.append("## The team")
    L.append("")
    L.append("| Agent | Role | Lane | State |")
    L.append("|---|---|---|---|")
    for aid, a in agents.get("agents", {}).items():
        role = a.get("role", "?")
        lane = {"claude": "integrate · judge · verify",
                "grok": "volume drafting · scaffolding · agent runs",
                "codex": "code build · mechanical verify · cross-check"}.get(aid, "—")
        L.append(f"| **{aid}** | {role} | {lane} | ACTIVE |")
    L.append("")
    L.append("## Work in flight")
    L.append("")
    if open_t:
        L.append("| Task | What | Who | State |")
        L.append("|---|---|---|---|")
        for t in open_t:
            L.append(f"| {t['id']} | {t['title']} | {t['agent']} | "
                     f"{STATE_EMOJI.get(t['state'], t['state'])} |")
    else:
        L.append("_Nothing in flight — both builders idle, standing by._")
    L.append("")
    L.append(f"## Done ({len(done_t)} tasks integrated)")
    L.append("")
    for t in done_t[-8:]:
        L.append(f"- ✅ **{t['id']}** {t['title']} — by {t['agent']}")
    L.append("")
    if scores.get("agents"):
        L.append("## Trust scores (observed, per lane)")
        L.append("")
        for aid, prof in scores["agents"].items():
            parts = ", ".join(f"{k} {v}" for k, v in prof.items())
            L.append(f"- **{aid}**: {parts}")
        L.append("")
    else:
        L.append("## Trust scores")
        L.append("")
        L.append("_No accepted scored tasks yet — profiles populate as tasks "
                 "complete (see `EXCHANGE/SCORING.md`)._")
        L.append("")
    L.append("## Precautions in force (why you can trust the output)")
    L.append("")
    L.append("- **Gates, not opinions:** every artifact must pass deterministic "
             "Python validators; the integrator re-runs them from its OWN copies "
             "(a builder can't grade itself).")
    L.append("- **Different brains check each other:** the three agents are three "
             "model families; each build is cross-verified by a different one — "
             "research calls this the 'universal antidote' to agents agreeing "
             "themselves into being wrong.")
    L.append("- **Fresh, short context per task:** builders start each job from a "
             "tight digest, not a giant history, because models degrade before "
             "their window fills.")
    L.append("- **The repo can't command the agents:** only signed, authenticated "
             "task messages from the integrator are instructions; everything else "
             "in the repo is treated as untrusted data.")
    L.append("- **Real enforcement is outside the AI:** sandboxes, permission "
             "rules, and gates stop bad actions — not just written 'don't' rules "
             "(which research shows can backfire).")
    L.append("- **Self-reported 'done' is never trusted:** acceptance needs a "
             "passed gate plus the integrator's independent re-check.")
    L.append("")
    L.append("## Latest activity")
    L.append("")
    for line in last5:
        L.append(f"- `{line}`")
    L.append("")
    out = os.path.join(ROOT, "EXCHANGE/STATUS.md")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"status: wrote {out} | {len(open_t)} open, {len(done_t)} integrated")

if __name__ == "__main__":
    main()
